"""empty message

Revision ID: 1e9636285d13
Revises: 9fe8544c7cc6
Create Date: 2024-12-10 16:29:53.579007

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e9636285d13"
down_revision = "9fe8544c7cc6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("topic", sa.String(length=100), nullable=True),
        sa.Column("subtopic", sa.String(length=100), nullable=True),
        sa.Column("publisher", sa.String(length=100), nullable=True),
        sa.Column("protocol", sa.String(length=100), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("unit", sa.String(length=100), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("string_value", sa.String(length=255), nullable=True),
        sa.Column("bool_value", sa.Boolean(), nullable=True),
        sa.Column("data_value", sa.String(length=255), nullable=True),
        sa.Column("sum_value", sa.Float(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=True),
        sa.Column("update_time", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    # ### end Alembic commands ###
