"""empty message

Revision ID: 9fe8544c7cc6
Revises: 58b88265d6f6
Create Date: 2024-10-21 18:46:21.640359

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9fe8544c7cc6"
down_revision = "58b88265d6f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dummy_model")
    op.create_unique_constraint(None, "alerts", ["id"])
    op.create_unique_constraint(None, "devices", ["id"])
    op.create_unique_constraint(None, "notifications", ["id"])
    op.create_unique_constraint(None, "tags", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", type_="unique")
    op.drop_constraint(None, "notifications", type_="unique")
    op.drop_constraint(None, "devices", type_="unique")
    op.drop_constraint(None, "alerts", type_="unique")
    op.create_table(
        "dummy_model",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="dummy_model_pkey"),
    )
    # ### end Alembic commands ###
