"""empty message

Revision ID: 45b46e720f7e
Revises: 1e9636285d13
Create Date: 2024-12-10 18:38:18.636257

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "45b46e720f7e"
down_revision = "1e9636285d13"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("channel_id", sa.String(), nullable=False))
    op.add_column(
        "messages", sa.Column("base_name", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "messages", sa.Column("base_unit", sa.String(length=100), nullable=False)
    )
    op.add_column("messages", sa.Column("base_value", sa.Float(), nullable=False))
    op.add_column("messages", sa.Column("base_time", sa.Integer(), nullable=False))
    op.add_column("messages", sa.Column("device_id", sa.Integer(), nullable=True))
    op.add_column("messages", sa.Column("user_id", sa.UUID(), nullable=True))
    op.alter_column(
        "messages", "publisher", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "messages", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "messages", "unit", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "messages",
        "value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column("messages", "time", existing_type=sa.INTEGER(), nullable=False)
    op.create_unique_constraint(None, "messages", ["id"])
    op.create_foreign_key(None, "messages", "devices", ["device_id"], ["id"])
    op.create_foreign_key(None, "messages", "user", ["user_id"], ["id"])
    op.drop_column("messages", "topic")
    op.drop_column("messages", "update_time")
    op.drop_column("messages", "timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "messages",
        sa.Column("update_time", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "messages",
        sa.Column("topic", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_constraint(None, "messages", type_="unique")
    op.alter_column("messages", "time", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "messages",
        "value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "messages", "unit", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "messages", "name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "messages", "publisher", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.drop_column("messages", "user_id")
    op.drop_column("messages", "device_id")
    op.drop_column("messages", "base_time")
    op.drop_column("messages", "base_value")
    op.drop_column("messages", "base_unit")
    op.drop_column("messages", "base_name")
    op.drop_column("messages", "channel_id")
    # ### end Alembic commands ###
