# name: Generate and Deploy API Documentation

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Use Node.js 16
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16

#       - name: Install redoc-cli
#         run: npm install -g redoc-cli

#       - name: Generate Swagger UI
#         run: redoc-cli bundle -o index.html swagger.json

#       - name: Deploy to GitHub Pages
#         uses: actions/deploy-pages@v1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           source: ./  # Replace with your documentation directory if needed
#           branch: gh-pages  # Replace with your desired branch

